services:

    frontend:
        container_name: jandolejs_cz_frontend
        build:
            context: .
            platforms:
                - linux/amd64
        image: ghcr.io/jandolejs/jandolejs_cz:latest
        ports:
            - 8076:80
        environment:
            BASE_URL: jandolejs.cz
            dsn: $dsn
            user: $user
            password: $password
        restart: unless-stopped
